[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❯](bold green)"

[time]
disabled=false
style = "fg:cyan"
time_format="%T"
format = "[$time]($style)"

[directory]
truncation_length = 8

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[docker_context]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[memory_usage]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "
